name: Nick Balestra
description: Try. Fail. Learn. Repeat
meta_description: "Nick Balestra's blog"


markdown: redcarpet
highlighter: pygments

paginate: 50
baseurl: /
domain_name: 'http://nick.balestra.ch'
google_analytics: 'UA-62842593-1'
disqus_shortname: 'nickbalestra'

# Details for the RSS feed generator
url:            'http://nick.balestra.ch'
author:         'Nick Balestra'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
